### ISSUE TITLE
Konverter nuget pakken til netstandard2.0

### ISSUE THREAD

**Issue by MariusGrandeAndersen** [digipost/api-client-shared-dotnet#20]
Jeg ser på historikken at dere skrev denne om til netstandard2.0 og deretter flyttet den til netcore2.2.

Dette blir feil og vi ber dere bytte tilbake til netstandard2.0.

En netcore2.2 pakke kan kun brukes av en netcore2.2 applikasjon. Microsoft er på versjon netcore3.1 nå, som dermed ikke kan importere pakken.

En netstandard2.0 pakke kan brukes av både netframework og alle nyere netcore versjoner.

Mer info:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by johnksv** [comment]
Hei @mariusandersen ,
Du har helt riktig at vi skrev om denne pakken til netstandard2.0 (https://github.com/digipost/api-client-shared-dotnet/releases/tag/v4.0.0) og deretter flyttet den til netcore2.2. (https://github.com/digipost/api-client-shared-dotnet/releases/tag/5.0.0). 

Hvis du ønsker å benytte netstandard2.0-pakken burde du altså bruke 4.0.0-versjonen. Det er ingen   forskjell i funksjonalitet mellom netcore2.2 (v5.0.0) og netstandard2.0 (v4.0.0).
netstandard2.0-pakken er tilgjengelig på NuGet her: https://www.nuget.org/packages/api-client-shared/

**Comment by johnksv** [comment]
Hei igjen @mariusandersen ,

Jeg har nå endret target til netstandard2.0. Pakken er tilgjengelig på NuGet som versjon 6.0.0 her: https://www.nuget.org/packages/Digipost.Api.Client.Shared/

Med det lukker jeg dette issuet. :)
