### ISSUE TITLE
log4net dependency.

### ISSUE THREAD

**Issue by sukchr** [digipost/api-client-shared-dotnet#5]
Hei, jeg ser at API-et har en dependency mot log4net, spesifikt versjon 2.0.4. Det er et ønske fra min side at logging-rammeverk abstraheres, slik at man unngår koblingen til en spesifikk versjon av log4net. Det blir fort krøll når ulike API-er har avhengigheter mot ulike versjoner av log4net..

Har dere mulighet til å vurdere bruk av Common.Logging, eller et annet API for abstraksjon av logg-rammeverk?

**Comment by kristianenge** [comment]
Flytter denne til [signatur klienten sitt repo](https://github.com/digipost/signature-api-client-dotnet/issues/44)
